#!/usr/bin/env sh

COMPOSE_FILE="docker-compose.yml"

if which dinghy > /dev/null 2>&1; then
    if ! dinghy ip > /dev/null 2>&1; then
        dinghy up
    fi
    eval $(dinghy env)
    COMPOSE_FILE="docker-compose-dinghy.yml"
fi
